version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: "xforwarded"
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json - Dkeycloak.profile.feature. upload_scripts-enabled
    ports:
      - "8080:8080"
    command:
      - start-dev
